inventory:
  build: .
  command: npm start
  ports:
  - "8888:8888"
  links:
  - mongodb
  - mongodb:mongodb.cloud66.local
  environment:
    - NODE_ENV=production
    - MONGODB_ADDRESS=mongodb
mongodb:
  image: mongo
